<?php

namespace iEXPackages\Payment\Engines\Message;

use iEXPackages\Payment\Exception\RuntimeException;
use Symfony\Component\HttpFoundation\RedirectResponse as HttpRedirectResponse;
use Symfony\Component\HttpFoundation\Response as HttpResponse;

/**
 * Abstract Response
 *
 * This abstract class implements ResponseInterface and defines a basic
 * set of functions that all Omnipay Requests are intended to include.
 *
 * Objects of this class or a subclass are usually created in the Request
 * object (subclass of AbstractRequest) as the return parameters from the
 * send() function.
 *
 * Example -- validating and sending a request:
 *
 * <code>
 *   $myResponse = $myRequest->send();
 *   // now do something with the $myResponse object, test for success, etc.
 * </code>
 */
abstract class AbstractResponse implements ResponseInterface
{
    /**
     * The embodied request object.
     */
    protected RequestInterface $request;

    /**
     * The data contained in the response.
     */
    protected array $data;

    /**
     * Constructor
     *
     * @param  RequestInterface  $request  the initiating request.
     */
    public function __construct(RequestInterface $request, array $data)
    {
        $this->request = $request;
        $this->data = $data;
    }

    /**
     * Get the initiating request object.
     */
    public function getRequest(): RequestInterface
    {
        return $this->request;
    }

    /**
     * Is the response successful?
     */
    public function isPending(): bool
    {
        return false;
    }

    /**
     * Does the response require a redirect?
     */
    public function isRedirect(): bool
    {
        return false;
    }

    /**
     * Is the response a transparent redirect?
     */
    public function isTransparentRedirect(): bool
    {
        return false;
    }

    /**
     * Is the transaction cancelled by the user?
     */
    public function isCancelled(): bool
    {
        return false;
    }

    /**
     * Get the response data.
     */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * Response Message
     *
     * @return null|string A response message from the payment gateway
     */
    public function getMessage(): ?string
    {
        return null;
    }

    /**
     * Response code
     *
     * @return null|string A response code from the payment gateway
     */
    public function getCode(): ?string
    {
        return null;
    }

    /**
     * Gateway Reference
     *
     * @return null|string A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference(): ?string
    {
        return null;
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     */
    public function getTransactionId(): mixed
    {
        return null;
    }

    /**
     * Gets the redirect target url.
     */
    public function getRedirectUrl(): ?string
    {
        return null;
    }

    /**
     * Get the required redirect method (either GET or POST).
     */
    public function getRedirectMethod(): string
    {
        return 'GET';
    }

    /**
     * Gets the redirect form data array, if the redirect method is POST.
     */
    public function getRedirectData(): array
    {
        return [];
    }

    /**
     * Получить готовый html форму для провайдера.
     *
     * @throws \Throwable
     */
    public function render(): string
    {
        //$this->validateRedirect();
        $view = \view('_parent.default_gateway', [
            'item' => $this->getData(),
            'redirectData' => $this->getRedirectData(),
            'redirectUrl' => $this->getRedirectUrl(),
            'redirectMethod' => $this->getRedirectMethod(),
        ]);

        return $view->render();
    }

    /**
     * Automatically perform any required redirect
     *
     * This method is meant to be a helper for simple scenarios. If you want to customize the
     * redirection page, just call the getRedirectUrl() and getRedirectData() methods directly.
     */
    public function redirect(): void
    {
        $this->getRedirectResponse()->send();
    }

    public function getRedirectResponse(): HttpRedirectResponse|HttpResponse
    {
        $this->validateRedirect();

        if ($this->getRedirectMethod() === 'GET') {
            return new HttpRedirectResponse($this->getRedirectUrl());
        }

        $hiddenFields = '';
        foreach ($this->getRedirectData() as $key => $value) {
            $hiddenFields .= sprintf(
                '<input type="hidden" name="%1$s" value="%2$s" />',
                htmlentities($key, ENT_QUOTES, 'UTF-8', false),
                htmlentities($value, ENT_QUOTES, 'UTF-8', false)
            )."\n";
        }

        $output = '<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Redirecting...</title>
</head>
<body onload="document.forms[0].submit();">
    <form action="%1$s" method="post">
        <p>Redirecting to payment page...</p>
        <p>
            %2$s
            <input type="submit" value="Continue" />
        </p>
    </form>
</body>
</html>';
        $output = sprintf(
            $output,
            htmlentities($this->getRedirectUrl(), ENT_QUOTES, 'UTF-8', false),
            $hiddenFields
        );

        return new HttpResponse($output);
    }

    /**
     * Validate that the current Response is a valid redirect.
     */
    protected function validateRedirect(): void
    {

        if (! $this->isRedirect()) {
            throw new RuntimeException('This response does not support redirection.');
        }

        if (empty($this->getRedirectUrl())) {
            throw new RuntimeException('The given redirectUrl cannot be empty.');
        }

        if (! in_array($this->getRedirectMethod(), ['GET', 'POST'])) {
            throw new RuntimeException('Invalid redirect method "'.$this->getRedirectMethod().'".');
        }
    }
}
